name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: get diff
      run: git diff ${{github.event.pull_request.head.sha}} ${{github.event.pull_request.base.sha}}
    - name: cpplint
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: ./check-git-clang-format-output.sh
    - name: build
      run: ./build.sh
    - name: run test
      run: ./hello_world/main
