name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cpplint
      run: ./pre-commit
    - name: build
      run: ./build.sh
    - name: run test
      run: ./hello_world/main
