name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: cpplint
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: ./check-git-clang-format-output.sh

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: get commits diff
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff ${{ github.event.before }} ${{ github.sha }})"
    - name: echo diff output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: build
      run: ./build.sh
    - name: run test
      run: ./hello_world/main
