name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      #- name: Dump GitHub context
      #env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: echo "$GITHUB_CONTEXT"
      #- name: cpplint
      #env:
      #GITHUB_CONTEXT: ${{ toJson(github) }}
      #run: ./check-git-clang-format-output.sh
    - name: get commits diff
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id -r ${{ github.sha }} | xargs)"
    - name: echo diff output
      run: |
        echo ${steps.getfile.outputs.files}}
    - name: build
      run: ./build.sh
    - name: run test
      run: ./hello_world/main
